name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        target: [alpine, debian]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # === SON DÜZELTME UYGULANMIŞ ADIM ===
      - name: Generate Docker tags
        id: meta
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository }}"
          tags="${IMAGE_ID}:${{ matrix.target }}"
          if [ "${{ matrix.target }}" = "alpine" ]; then
            tags=$(printf "%s\n%s" "$tags" "${IMAGE_ID}:latest")
          fi
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "${tags}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: ${{ matrix.target }}
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: true